---
os: linux
dist: bionic
language: ruby
git:
  submodules: true
install:
  - gem install mdl
script:
  # Markdown linting
  # https://github.com/markdownlint/markdownlint
  # MD002: first level header is managed by hugo theme
  # MD024: several sections repeat the header name, may be reviewed later
  - mdl -s relaxed -s style.rb -r ~MD002,~MD024 content/
  # building static content with hugo
  - ./binaries/linux64/hugo
deploy:
  # https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  # Use dpl v2
  edge: true
  # Keep generated files before uploading, required
  cleanup: false
  # Be verbose for debugging
  verbose: true
  # Source directory
  local_dir: public
  # Strategy
  strategy = git
  # Target repository
  repo: gwarf/gwarf.github.io
  # Target branch
  target_branch: master
  # Set in the settings page of the repository, as a secure variable
  token: $GITHUB_TOKEN
  # Custom FQDN for GitHub pages
  fqdn: blog.bapt.name
  on:
    branch: master
