---
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: deploy

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      # Install markdown linter
      # https://github.com/markdownlint/markdownlint
      - run: sudo gem install mdl
      # Checkout the repository
      - checkout
      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init
      # Lint markdown
      # MD002: first level header is managed by hugo theme
      # MD024: several sections repeat the header name, may be reviewed later
      - run: mdl -s relaxed -s .mdl-style.rb -r ~MD002,~MD024 content/
      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d ~/public
      # Commit changes to a new local repository
      - run:
          name: Deploy to GitHub pages
          working_directory: ~/public
          command: |
            echo 'blog.bapt.name' > CNAME
            git config --global user.email "baptiste@bapt.name"
            git config --global user.name "CircleCI Bot"
            git init . && git add --all
            git commit -m "Automated publish to gh-pages [ci skip]"
      # Add remote repostory
      - run:
          name: Deploy to GitHub pages
          working_directory: ~/public
          command: git remote add gh "https://${GITHUB_PERSONAL_TOKEN}@github.com/gwarf/gwarf.github.io"
      # Push the generated files back to github
      - run:
          name: Deploy to GitHub pages
          working_directory: ~/public
          command: |
            git branch -vvv
            git remote -vvv
            git push -vvv --force gh master
            echo "Success"
