---
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: deploy

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      # Install markdown linter
      # https://github.com/markdownlint/markdownlint
      - run: sudo gem install mdl
      # Checkout the repository
      - checkout
      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init
      # Lint markdown
      - run: mdl --ignore-front-matter --style .mdl-style.rb content/
      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d ~/public
      - run:
          name: Commit changes to a new local repository
          working_directory: ~/public
          command: |
            echo 'blog.bapt.name' > CNAME
            git config --global user.email "baptiste@bapt.name"
            git config --global user.name "CircleCI Bot"
            git init . && git add --all
            git commit -m "Automated publish to gh-pages [ci skip]"
      - run:
          name: Push the generated files back to GitHub pages
          working_directory: ~/public
          command: |
            git push -vvv --force "git:@github.com:gwarf/gwarf.github.io.git" master
            echo "Success"
